PUT http://localhost:5000/v1/api/users/14
Content-Type: application/json

{
    "name": "Gita Amelia Updated",
    "email": "gita.amelia@example.com",
    "password": "GitaAmel!a",
    "divisi": "R&D",
    "position": "Lead",
    "role": "ADMIN"
}

###
GET http://localhost:5000/v1/api/users?page=1&limit=10
Content-Type: application/json


###
GET http://localhost:5000/v1/api/users/1
Content-Type: application/json
