POST http://localhost:3000/v1/api/users
Content-Type: application/json

{
    "name": "Fajar Hidayat",
    "email": "fajar.hidayat@example.com",
    "password": "fajarhidayatpw",
    "divisi": "IT",
    "position": "Technician",
    "roles": "USER"
}
###
PUT http://localhost:3000/v1/api/users/1
Content-Type: application/json

{
    "name": "John Doe Updated",
    "email": "john.doe@example.com",
    "password": "password123",
    "divisi": "IT",
    "position": "Developer",
    "roles": "USER"
}

###
GET http://localhost:3000/v1/api/users?page=1&limit=3
Content-Type: application/json


###
GET http://localhost:3000/v1/api/users/1
Content-Type: application/json
