POST http://localhost:5000/api/v1/materials
Content-Type: application/json

{
  "title": "NestJS Fundamentals",
  "description": "An in-depth look at the core concepts of NestJS.",
  "topicId": 9,
  "fileUrl": "https://example.com/nestjs-fundamentals.pdf"
}

###
PUT http://localhost:5000/api/v1/materials/2
Content-Type: application/json

{
  "title": "NestJS Fundamentals Updated",
  "description": "An in-depth look at the core concepts of NestJS, updated.",
  "topicId": 9,
  "fileUrl": "https://example.com/nestjs-fundamentals-v2.pdf"
}

###
GET http://localhost:5000/api/v1/materials/topic/9?page=1&limit=10
Content-Type: application/json

###
GET http://localhost:5000/api/v1/materials/2
Content-Type: application/json


###
DELETE http://localhost:5000/api/v1/materials/1
Content-Type: application/json

###
GET http://localhost:5000/api/v1/materials/count
Content-Type: application/json

###
GET http://localhost:5000/api/v1/materials/material/populars
Content-Type: application/json