POST http://localhost:3000/v1/api/auth/register
Content-Type: application/json

{
    "name": "Rijal Rifais",
    "email": "rijal@ppu.co.id1",
    "password": "ss",
    "divisi": "IT",
    "position": "TechLead",
    "roles": "ADMIN"
}

###
POST http://localhost:3000/v1/api/auth/login
Content-Type: application/json

{
    "email" : "rijal@ppu.co.id12",
    "password": "rijal123"
}
###
DELETE  http://localhost:3000/v1/api/auth/logout
Content-Type: application/json
###
GET http://localhost:3000/v1/api/auth/profile
Content-Type: application/json